dic_palabras = ["¡Hágalo ahora!",
"¡Llame gratis!",
"Ahorre",
"Asombroso",
"Aumente las ventas",
"Compra directa",
"Costos",
"Dirección de cobro",
"Gane dinero",
"Oferta",
"Gratis!",
"Ingreso",
"Prometerte",
"Promoción",
"Reintegro",
"Sexo",
"Sin riesgo",
"Sin trucos",
"Trabaje desde casa",
"Urgente",
"Ventas"
"GRATIS"
"Atención",
"Llame ahora",
"Duplique su ingreso",
"Información que usted solicitó",
"Libertad financiera",
"Haga clic aquí",
"Esto no es spam",
"Consolidar"," $ $ $",
"salga de su deuda",
"elimine la deuda",
"reduzcasu tasa de hipoteca",
"refinanciar",
"tarifas más seguras",
"seguros de vida",
"préstamos"
]

dic_fuentes = ["Arial",
"Tahoma",
"Trebuchet MS",
"Verdana",
"Georgia",
"Times New Roman",
"Times",
"Courier",
"Andale mono",
"Comic Sans MS" ]